# Generated by Django 5.0.3 on 2024-07-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='rich_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
